name: Main
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:

permissions:
  actions: write
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.1'

      - name: Run tests
        run: go test -coverprofile=coverage.out

      - uses: qltyai/qlty-action/coverage@main
        with:
          coverage-token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          file: coverage.out
          strip-prefix: sample/
